export const themes = {
  Vrienden: [
    "Beste vriend", "Groepsapp", "Inside joke", "Bijnaam", "Selfie",
    "Reünie", "Huisgenoot", "Vriendschap", "Geheim", "High five",
    "Knuffel", "Roddelen", "Bromance", "BFF", "Jeugdvriend",
    "Klasgenoot", "Collega", "Buurmeisje", "Buurjongen", "Teamgenoot",
    "Penvriend", "Internetvriend", "Vriendenboekje", "Groepsfoto", "Voicebericht",
    "Tikkie", "Meme", "Screenshot", "Videobellen", "Spraakmemo",
    "Roadtrip", "Festival", "Karaoke", "Filmavond", "Spelletjesavond",
    "Slaapfeest", "Kroegentocht", "Barbecue", "Pubquiz", "Escape room",
    "Bowlen", "Kamperen", "Stedentrip", "Concert", "Picknick",
    "Blind vertrouwen", "Goede raad", "Luisterend oor", "Peptalk", "Schouderklopje",
    "Ruzie", "Excuses", "Verzoening", "Belofte", "Loyaliteit",
    "Surpriseparty", "Verjaardag", "Housewarming", "Vrijgezellenfeest", "Gala",
    "Friends", "Central Perk", "Rachel Green", "Joey Tribbiani", "Chandler Bing",
    "Harry Potter", "Ron Wemel", "Hermelien", "Frodo", "Sam Gewissies",
    "Timon en Pumbaa", "Woody en Buzz", "Tom en Jerry", "Suske en Wiske", "Buurman en Buurman",
    "Bassie en Adriaan", "Ernie en Bert", "Kuifje", "Kapitein Haddock", "Scooby-Doo",
    "Shrek", "Ezel", "SpongeBob", "Patrick Ster", "Mario en Luigi",
    "The Avengers", "The Beatles", "Spice Girls", "K3", "Snollebollekes",
    "Whatsapp", "Instagram", "Snapchat", "TikTok", "Discord",
    "Spotify", "Netflix", "PlayStation", "Nintendo", "YouTube",
    "Vriendendienst", "Grapjas", "Gangmaker", "Reisgenoot", "Sportmaatje",
    "Dubbeldate", "Samenwonen", "Logeerpartij", "Gedeelde rekening", "Cadeaugroep",
    "Vriendenkring", "Hartsvriendin", "Kameraad", "Bondgenoot", "Vertrouweling",
    "Polonaise", "Potje kaarten", "Terrasje", "Dagje strand", "Voetbalteam"
  ],
  Terras: [
    "Bitterballen", "Parasol", "Dienblad", "Menukaart", "Fooi",
    "Ober", "Terrasstoel", "Zonnescherm", "Onderzetter", "Asbak",
    "Barkruk", "Kassabon", "Reservering", "Rekening", "Pinautomaat",
    "Speciaalbier", "Tapbier", "Radler", "Rosé", "Prosecco",
    "Sangria", "Mojito", "Gin-tonic", "Aperol Spritz", "Espresso martini",
    "Cappuccino", "Muntthee", "IJskoffie", "Limonade", "Verse jus",
    "Spa rood", "Tonic", "Huiswijn", "Alcoholvrij bier", "Kopstootje",
    "Borrelplank", "Nacho's", "Olijven", "Kaastengels", "Borrelnootjes",
    "Tosti", "Uitsmijter", "Hamburger", "Saté", "Appeltaart",
    "Cheesecake", "Dame blanche", "Slagroom", "Kruidenboter", "Broodmandje",
    "Rondje geven", "Proosten", "Happy hour", "Laatste ronde", "Rekening delen",
    "Pinnen", "Contactloos betalen", "Tikkie", "Kleingeld", "Drankkaart",
    "Zonsondergang", "Zomeravond", "Avondzon", "Plensbui", "Windvlaag",
    "Terrasverwarmer", "Windscherm", "Zitkussen", "Stoepbord", "Tafelkaars",
    "Strandtent", "Dakterras", "Waterkant", "Marktplein", "Boulevard",
    "Eetcafé", "Grand café", "Lunchroom", "Koffiebar", "Wijnbar",
    "Cocktailbar", "Bruin café", "Snackbar", "IJssalon", "Biergarten",
    "Barista", "Barman", "Sommelier", "Chef-kok", "Vaste klant",
    "Heineken", "Amstel", "Hertog Jan", "Duvel", "La Chouffe",
    "Corona", "Desperados", "Bacardi", "Martini", "Chocomel",
    "Schuimkraag", "Bierdopje", "Kurkentrekker", "Cocktailprikker", "IJsblokjes",
    "Rietje", "Servet", "Karaaf", "Pepervaatje", "Suikerzakje",
    "Vol terras", "Vrije stoel", "Stamtafel", "Tafelnummer", "Wachttijd",
    "Glas omstoten", "Verkeerde bestelling", "Straatmuzikant", "Middagborrel", "Dagmenu"
  ],
  "Date night": [
    "Eerste date", "Blind date", "Dubbeldate", "Eerste kus", "Vlinders",
    "Flirten", "Oogcontact", "Compliment", "Chemie", "Vonkje",
    "Kaarslicht", "Rode rozen", "Liefdesbrief", "Serenade", "Champagne",
    "Parfum", "Boeket", "Dessert", "Dresscode", "Tafel voor twee",
    "Bioscoop", "Restaurant", "Picknick", "Sterrenkijken", "Strandwandeling",
    "Rooftopbar", "Museum", "Theater", "Concert", "Kerstmarkt",
    "Midgetgolf", "Bowlen", "Schaatsen", "Karaoke", "Dansles",
    "Samen koken", "Sushi", "Pizza", "Ontbijt op bed", "Weekendje weg",
    "Datingapp", "Tinder", "Bumble", "Swipe rechts", "Profielfoto",
    "Openingszin", "Telefoonnummer", "Hartjesemoji", "Goedemorgen-appje", "Ghosten",
    "Friendzone", "Soulmate", "Cupido", "Ware liefde", "Gebroken hart",
    "Jaloezie", "Afwijzing", "Ex-partner", "Tweede kans", "Relatiepauze",
    "Huwelijksaanzoek", "Verlovingsring", "Bruiloft", "Huwelijksreis", "Jubileum",
    "Valentijnsdag", "Samenwonen", "Schoonfamilie", "Trouwen", "Liefdesbaby",
    "Titanic", "The Notebook", "Love Actually", "Pretty Woman", "La La Land",
    "Grease", "Dirty Dancing", "Bridgerton", "Romeo en Julia", "The Bachelor",
    "Ken en Barbie", "Mickey en Minnie", "Donald en Katrien", "Shrek en Fiona", "Lady en de Vagebond",
    "Beyoncé en Jay-Z", "David en Victoria", "Máxima en Willem-Alexander", "Taylor Swift", "Bruno Mars",
    "Casanova", "Aphrodite", "Eiffeltoren", "Parijs", "Venetië",
    "Gondel", "Liefdesslotje", "Fotohokje", "Open haard", "Rozenblaadjes",
    "Hand vasthouden", "Lange knuffel", "Afscheidskus", "Arm om schouder", "Jas uitlenen",
    "Ongemakkelijke stilte", "Eerste indruk", "Diep gesprek", "Guilty pleasure", "Geheime aanbidder",
    "Liefdeslied", "Romcom", "Slowdance", "Liefdesgedicht", "Kus onder mistletoe",
    "Chocolade", "Aardbeien", "Cocktail", "Rode wijn", "Lovebird"
  ],
  Vakantie: [
    "Paspoort", "Koffer", "Handbagage", "Boardingpass", "Vliegticket",
    "Douane", "Vliegveld", "Bagageband", "Gate", "Raamplaats",
    "Turbulentie", "Jetlag", "Tussenlanding", "Reisverzekering", "Visum",
    "Camping", "Tent", "Slaapzak", "Luchtbed", "Caravan",
    "Camper", "Glamping", "Kampvuur", "Zaklamp", "Hangmat",
    "Hotelkamer", "Hostel", "Roomservice", "Minibar", "All-inclusive",
    "Zwembad", "Strandlaken", "Slippers", "Zonnebrand", "Zonnebril",
    "Souvenir", "Ansichtkaart", "Reisgids", "Routekaart", "Fotocamera",
    "Roadtrip", "Huurauto", "Tolweg", "Dakkoffer", "Tankstation",
    "Treinreis", "Interrail", "Nachttrein", "Cruiseschip", "Veerboot",
    "Safari", "Excursie", "Eilandhoppen", "Stedentrip", "Rugzak",
    "Snorkelen", "Duiken", "Surfen", "Waterskiën", "Parasailen",
    "Skiën", "Snowboarden", "Après-ski", "Skilift", "Lawine",
    "Bergtop", "Waterval", "Gletsjer", "Woestijn", "Koraalrif",
    "Palmboom", "Zandkasteel", "Vuurtoren", "Lagune", "Noorderlicht",
    "Eiffeltoren", "Big Ben", "Colosseum", "Sagrada Família", "Vrijheidsbeeld",
    "Chinese Muur", "Taj Mahal", "Machu Picchu", "Grand Canyon", "Niagarawatervallen",
    "Parijs", "Londen", "Rome", "Barcelona", "New York",
    "Ibiza", "Bali", "Hawaï", "Tenerife", "Griekenland",
    "Turkije", "Thailand", "Australië", "IJsland", "Zuid-Afrika",
    "Schiphol", "KLM", "Transavia", "Ryanair", "Booking.com",
    "Airbnb", "TUI", "Lonely Planet", "Google Maps", "Tripadvisor",
    "Tijdsverschil", "Taalbarrière", "Afdingen", "Vreemde valuta", "Lokale keuken",
    "Muggenbeet", "Vakantieliefde", "Pech onderweg", "Vertraagde vlucht", "Thuiskomst"
  ],
  Huisfeest: [
    "Discobal", "Confetti", "Ballonnen", "Slingers", "Feesthoed",
    "Dansvloer", "Playlist", "DJ", "Luidspreker", "Microfoon",
    "Stroboscoop", "Rookmachine", "Glowstick", "Polonaise", "Karaoke",
    "Luchtgitaar", "Slowdance", "Moonwalk", "Macarena", "Limbo",
    "Beer pong", "Twister", "Drankspel", "Kaartspel", "Stoelendans",
    "Hints", "Pubquiz", "Ik heb nooit", "Waarheid of durven", "Danswedstrijd",
    "Bierkrat", "Wijnfles", "Shotglaasje", "Cocktailshaker", "Punch",
    "Chips", "Borrelnootjes", "Pizza", "Cupcake", "Verjaardagstaart",
    "Flesopener", "Plastic beker", "IJsblokjes", "Servet", "Vuilniszak",
    "Deurbel", "Gastenlijst", "Garderobe", "Jassenberg", "Huisregels",
    "Buren", "Boze buurman", "Geluidsoverlast", "Plakkerige vloer", "Kapotte vaas",
    "Verstopte wc", "Sleutel kwijt", "Jas verwisseld", "Gemorst drankje", "Verdwaalde gast",
    "Feestbeest", "Muurbloempje", "Gangmaker", "Laatkomer", "Slaapgast",
    "Nuchtere chauffeur", "Pizzabezorger", "DJ-booth", "Afterparty", "Opruimploeg",
    "Verjaardagsfeest", "Themafeest", "Halloweenfeest", "Kerstfeest", "Studentenfeest",
    "Tuinfeest", "Surpriseparty", "Nieuwjaarsfeest", "Foute party", "Pyjamafeest",
    "ABBA", "Queen", "Beyoncé", "Lady Gaga", "Bruno Mars",
    "K3", "Snollebollekes", "Guus Meeuwis", "André Hazes", "Joost Klein",
    "Dancing Queen", "YMCA", "Mamma Mia", "Links Rechts", "Engelbewaarder",
    "Spotify", "TikTok", "Disco",
    "Champagnekurk", "Sterretje", "Party popper", "Feestbril", "Pruik",
    "Masker", "Glitters", "Verkleedkist", "Hawaïkrans",
    "Kaarsjes uitblazen", "Cadeau uitpakken", "Speech", "Proosten", "Groepsfoto",
    "Meezingen", "Verzoeknummer", "Valse noot", "Handen omhoog",
    "Nachtbus", "Taxi", "Kater", "Ochtend erna"
  ]
};
