export const themes = {
  Vrienden: [
    "Beste vriend", "Vriendin", "Vriendengroep", "Huisgenoot", "Klasgenoot",
    "Teamgenoot", "Collega", "Buurman", "Buurvrouw", "Jeugdvriend",
    "Bijnaam", "Geheim", "Grap", "Ruzie", "Excuses",
    "Vertrouwen", "Belofte", "Advies", "Hulp", "Troosten",
    "Knuffel", "High five", "Glimlach", "Lachen", "Roddelen",
    "Groepsapp", "Videobellen", "Selfie", "Groepsfoto", "Spraakbericht",
    "Emoji", "Meme", "Tikkie", "Telefoon", "Koptelefoon",
    "Verjaardag", "Cadeau", "Feestje", "Uitnodiging", "Surprise",
    "Filmavond", "Spelletjesavond", "Slaapfeest", "Karaoke", "Barbecue",
    "Picknick", "Festival", "Concert", "Vakantie", "Weekendje weg",
    "Strand", "Terras", "Bioscoop", "Pretpark", "Dierentuin",
    "Bowlen", "Voetballen", "Dansen", "Gamen", "Winkelen",
    "Pizza", "Friet", "Popcorn", "IJsje", "Koffie",
    "Schoolplein", "Kantine", "Kroeg", "Studentenhuis", "Sportclub",
    "Vriendenboekje", "Fotoboek", "Armband", "Sleutelhanger", "Ansichtkaart",
    "Friends", "Harry Potter", "Ron Wemel", "Hermelien", "Mickey Mouse",
    "Donald Duck", "Tom en Jerry", "Timon en Pumbaa", "Woody en Buzz", "Mario en Luigi",
    "Bassie en Adriaan", "Buurman en Buurman", "Ernie en Bert", "Suske en Wiske", "Scooby-Doo",
    "Shrek", "SpongeBob", "The Avengers", "K3", "Spice Girls",
    "WhatsApp", "Instagram", "TikTok", "Snapchat", "YouTube",
    "Spotify", "Netflix", "PlayStation", "Nintendo", "FaceTime",
    "Roadtrip", "Logeren", "Samenwonen", "Dubbeldate", "Reünie",
    "Vriendendienst", "Grapjas", "Feestbeest", "Reisgenoot", "Sportmaatje",
    "Goede raad", "Luisterend oor", "Schouderklopje", "Afscheidsknuffel", "Vriendschap"
  ],
  Terras: [
    "Terras", "Tafel", "Stoel", "Parasol", "Menukaart",
    "Ober", "Bediening", "Bestelling", "Rekening", "Fooi",
    "Dienblad", "Glas", "Kopje", "Rietje", "Servet",
    "Onderzetter", "Asbak", "Barkruk", "Zitkussen", "Zonnescherm",
    "Bitterballen", "Friet", "Nacho's", "Olijven", "Kaastengels",
    "Hamburger", "Tosti", "Salade", "Appeltaart", "IJsje",
    "Slagroom", "Ketchup", "Mayonaise", "Mosterd", "Broodmandje",
    "Koffie", "Thee", "Cappuccino", "Limonade", "Cola",
    "Water", "Sinaasappelsap", "Chocomel", "IJskoffie", "Milkshake",
    "Bier", "Wijn", "Rosé", "Champagne", "Radler",
    "Cocktail", "Mojito", "Sangria", "Gin-tonic", "Speciaalbier",
    "IJsblokjes", "Citroen", "Bierdopje", "Kurkentrekker",
    "Proosten", "Rondje geven", "Pinnen", "Tikkie", "Reserveren",
    "Wachten", "Bestellen", "Afrekenen", "Glas omgooien", "Rekening delen",
    "Zon", "Schaduw", "Regen", "Wind", "Zomeravond",
    "Zonsondergang", "Avondzon", "Hete dag", "Plensbui", "Terrasverwarmer",
    "Strandtent", "Café", "Snackbar", "Lunchroom", "Koffiebar",
    "Wijnbar", "Cocktailbar", "IJssalon", "Pannenkoekenhuis", "Restaurant",
    "Plein", "Boulevard", "Dakterras", "Waterkant", "Stamtafel",
    "Heineken", "Amstel", "Hertog Jan", "Coca-Cola", "Fanta",
    "Spa rood", "Lipton", "Douwe Egberts", "Magnum", "Cornetto",
    "Happy hour", "Laatste ronde", "Vol terras", "Vrije stoel", "Vaste klant",
    "Tafelnummer", "Dagschotel", "Borrelen", "Lunch", "Diner",
    "Barman", "Barista", "Chef-kok", "Kassa", "Bonnetje",
    "Peper"
  ],
  "Date night": [
    "Eerste date", "Blind date", "Dubbeldate", "Eerste kus", "Verliefd",
    "Vlinders", "Flirten", "Oogcontact", "Compliment", "Glimlach",
    "Knuffel", "Kus", "Hand vasthouden", "Arm omheen", "Afscheid",
    "Kaarslicht", "Rozen", "Chocolade", "Liefdesbrief", "Cadeau",
    "Parfum", "Boeket", "Hartje", "Cupido", "Serenade",
    "Bioscoop", "Restaurant", "Terras", "Picknick", "Strandwandeling",
    "Park", "Theater", "Concert", "Museum", "Kermis",
    "Bowlen", "Midgetgolf", "Schaatsen", "Karaoke", "Dansen",
    "Samen koken", "Film kijken", "Sterren kijken", "Weekendje weg", "Ontbijt op bed",
    "Pizza", "Sushi", "Pasta", "Dessert", "IJsje",
    "Rode wijn", "Champagne", "Cocktail", "Aardbeien", "Slagroom",
    "Tinder", "Bumble", "Datingapp", "Swipe", "Match",
    "Profielfoto", "Openingszin", "Chatbericht", "Telefoonnummer", "Hartjesemoji",
    "Zenuwen", "Stilte", "Eerste indruk", "Diep gesprek", "Slecht gesprek",
    "Te laat", "Dresscode", "Rekening", "Tafel voor twee", "Taxi",
    "Vriendje", "Vriendinnetje", "Relatie", "Ex", "Friendzone",
    "Jaloezie", "Afwijzing", "Verkering", "Soulmate", "Ware liefde",
    "Samenwonen", "Trouwen", "Bruiloft", "Verlovingsring", "Huwelijksaanzoek",
    "Jubileum", "Valentijnsdag", "Huwelijksreis", "Schoonfamilie", "Liefdesbaby",
    "Titanic", "The Notebook", "Love Actually", "Grease", "Dirty Dancing",
    "Romeo en Julia", "Barbie en Ken", "Mickey en Minnie", "Shrek en Fiona", "Donald en Katrien",
    "Taylor Swift", "Bruno Mars", "Ed Sheeran", "Parijs", "Venetië",
    "Eiffeltoren", "Gondel", "Fotohokje", "Open haard", "Zonsondergang",
    "Liefdeslied", "Romantische film", "Slowdance", "Gebroken hart", "Geheime liefde"
  ],
  Vakantie: [
    "Vakantie", "Paspoort", "Koffer", "Rugzak", "Vliegticket",
    "Vliegveld", "Vliegtuig", "Piloot", "Stewardess", "Douane",
    "Gate", "Boardingpass", "Bagage", "Raamplaats", "Bagageband",
    "Trein", "Bus", "Auto", "Boot", "Taxi",
    "Camping", "Tent", "Slaapzak", "Luchtbed", "Caravan",
    "Camper", "Hotel", "Hotelkamer", "Zwembad", "Vakantiehuis",
    "Strand", "Zee", "Zand", "Zonnebrand", "Zonnebril",
    "Slippers", "Strandlaken", "Strandbal", "Zandkasteel", "Schelp",
    "Palmboom", "Hangmat", "Cocktail", "Kokosnoot", "IJsje",
    "Zwemmen", "Duiken", "Snorkelen", "Surfen", "Skiën",
    "Wandelen", "Fietsen", "Kamperen", "Varen", "Zonnen",
    "Berg", "Waterval", "Eiland", "Woestijn", "Bos",
    "Meer", "Rivier", "Grot", "Vulkaan", "Noorderlicht",
    "Souvenir", "Ansichtkaart", "Reisgids", "Landkaart", "Fotocamera",
    "Roadtrip", "Safari", "Excursie", "Stedentrip", "Cruise",
    "Parijs", "Londen", "Rome", "Barcelona", "New York",
    "Ibiza", "Bali", "Hawaï", "Tenerife", "Amsterdam",
    "Frankrijk", "Spanje", "Italië", "Griekenland", "Turkije",
    "Duitsland", "Portugal", "Thailand", "Australië", "Amerika",
    "Eiffeltoren", "Big Ben", "Colosseum", "Vrijheidsbeeld", "Chinese Muur",
    "Piramides", "Disneyland", "Schiphol", "KLM", "Airbnb",
    "Google Maps",
    "Jetlag", "Tijdsverschil", "Muggenbeet", "Vakantieliefde",
    "Vertraagd", "Verdwaald", "Pech", "Files", "Thuiskomst",
    "Minibar", "Roomservice", "All-inclusive", "Campingstoel", "Zaklamp"
  ],
  Huisfeest: [
    "Huisfeest", "Verjaardag", "Feestje", "Gasten", "Uitnodiging",
    "Deurbel", "Gastenlijst", "Jassen", "Cadeau", "Buren",
    "Ballonnen", "Slingers", "Confetti", "Discobal", "Feesthoed",
    "Kaarsjes", "Glitters", "Pruik", "Masker", "Feestbril",
    "Dansvloer", "Muziek", "Playlist", "DJ", "Luidspreker",
    "Microfoon", "Karaoke", "Disco", "Lichtshow", "Rookmachine",
    "Dansen", "Meezingen", "Springen", "Polonaise", "Slowdance",
    "Moonwalk", "Macarena", "Limbo", "Luchtgitaar", "Stoelendans",
    "Beer pong", "Twister", "Kaartspel", "Drankspel", "Hints",
    "Pubquiz", "Dobbelsteen", "Spelletjes",
    "Bier", "Wijn", "Champagne", "Cocktail", "Frisdrank",
    "Shotje", "Plastic beker", "Flesopener", "IJsblokjes", "Rietje",
    "Chips", "Pizza", "Taart", "Cupcake", "Borrelnootjes",
    "Kaas", "Toastje", "Hotdog", "Snoep", "Popcorn",
    "Verjaardagstaart", "Kaarsjes uitblazen", "Cadeau uitpakken", "Verjaardagslied", "Proosten",
    "Groepsfoto", "Selfie", "Speech", "Verrassing", "Aftellen",
    "Feestbeest", "Gangmaker", "Muurbloempje", "Laatkomer", "Slaapgast",
    "Boze buurman", "Geluidsoverlast", "Gemorst drankje", "Kapotte vaas", "Plakkerige vloer",
    "Verstopte wc", "Sleutel kwijt", "Taxi", "Nachtbus", "Kater",
    "Afterparty", "Blijven slapen", "Opruimen", "Vuilniszak", "Stofzuiger",
    "ABBA", "Queen", "K3", "Snollebollekes", "André Hazes",
    "Beyoncé", "Lady Gaga", "Bruno Mars", "Taylor Swift", "Joost Klein",
    "Dancing Queen", "YMCA", "Mamma Mia", "Links Rechts", "Europapa",
    "Spotify", "TikTok", "Foute muziek",
    "Halloween", "Kerstfeest", "Tuinfeest", "Pyjamafeest"
  ]
};
